In [1]:
import pandas as pd
import numpy as np

data = {
    "Name": ["John", "Alice", "Bob", None, "Emma"],
    "Age": [25, np.nan, 30, 28, np.nan],
    "Salary": [50000, 60000, np.nan, 55000, 65000],
    "Department": ["HR", "IT", None, "Finance", "IT"]
}

df = pd.DataFrame(data)

print("Original Dataset:")
df

Original Dataset:

    Name   Age   Salary Department
0   John  25.0  50000.0         HR
1  Alice   NaN  60000.0         IT
2    Bob  30.0      NaN       None
3   None  28.0  55000.0    Finance
4   Emma   NaN  65000.0         IT

In [2]:
# Check missing values

print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Name          1
Age           2
Salary        1
Department    1
dtype: int64

In [4]:
# Fill missing values

df["Age"].fillna(df["Age"].mean(), inplace=True)
df["Salary"].fillna(df["Salary"].mean(), inplace=True)
df["Department"].fillna(df["Department"].mode()[0], inplace=True)
df["Name"].fillna("Unknown", inplace=True)

print("Dataset After Filling Missing Values:")
df

Dataset After Filling Missing Values:

/tmp/ipykernel_11899/3410911233.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)
/tmp/ipykernel_11899/3410911233.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(df["Salary"].mean(), inplace=True)
/tmp/ipykernel_11899/3410911233.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Department"].fillna(df["Department"].mode()[0], inplace=True)
/tmp/ipykernel_11899/3410911233.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Name"].fillna("Unknown", inplace=True)

      Name        Age   Salary Department
0     John  25.000000  50000.0         HR
1    Alice  27.666667  60000.0         IT
2      Bob  30.000000  57500.0         IT
3  Unknown  28.000000  55000.0    Finance
4     Emma  27.666667  65000.0         IT

In [5]:
# Check for duplicate rows

print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [6]:
# Final Cleaned Dataset

print("Cleaned Dataset:")
df

Cleaned Dataset:

      Name        Age   Salary Department
0     John  25.000000  50000.0         HR
1    Alice  27.666667  60000.0         IT
2      Bob  30.000000  57500.0         IT
3  Unknown  28.000000  55000.0    Finance
4     Emma  27.666667  65000.0         IT